#pragma once
#define BOOMERANG_STATE_MOVE "MOVE"
#define BOOMERANG_STATE_ATTACK "ATTACK"
#define BOOMERANG_STATE_SPIN "SPIN"
const D3DXVECTOR2 BOOMERANG_BROTHER__BBOX = D3DXVECTOR2(16 * 3, 24 * 3);
const float  BOOMERANG_BROTHER_GRAVITY = 0.00093f * 2;