#pragma once
#define BOOMERANG_STATE_MOVE "MOVE"
#define BOOMERANG_STATE_ATTACK "ATTACK"
#define BOOMERANG_STATE_SPIN "SPIN"
#define BOOMERANG_STATE_IDLE "IDLE"
const D3DXVECTOR2 BOOMERANG_BROTHER__BBOX = D3DXVECTOR2(16 * 3, 24 * 3);
const D3DXVECTOR2 BOOMERANG_BBOX = D3DXVECTOR2(16 * 3, 16 * 3);
const float  BOOMERANG_BROTHER_GRAVITY = 0.00093f * 2;
const float  BOOMERANG_BROTHER_VELOCITY = 0.1f;
const float  DISTANCE_CAN_THROW_ONCE = 200.0f;
const float  DISTANCE_CAN_THROW_TWICE = 150.0f;
const int BOUNDARY = 100;

const float  BOOMERANG_VEL_X = 0.2f;
const float  BOOMERANG_VEL_Y = 0.2f;

const int ATTACK_TIME_THROW_ONCE = 1000;
const int ATTACK_TIME_THROW_TWICE = 800;
const int IDLE_TIME = 500;
