#pragma once
#define BOOMERANG_STATE_MOVE "MOVE"
#define BOOMERANG_STATE_ATTACK "ATTACK"
#define BOOMERANG_STATE_SPIN "SPIN"
const D3DXVECTOR2 BOOMERANG_BROTHER__BBOX = D3DXVECTOR2(16 * 3, 24 * 3);
const D3DXVECTOR2 BOOMERANG_BBOX = D3DXVECTOR2(16 * 3, 16 * 3);
const float  BOOMERANG_BROTHER_GRAVITY = 0.00093f * 2;
const float  BOOMERANG_BROTHER_VELOCITY = 0.05f;
const float  DISTANCE_CAN_THROW_ONCE = 300.0f;
const float  DISTANCE_CAN_THROW_TWICE = 200.0f;
const int BOUNDARY = 100;


const float  BOOMERANG_VEL_X = 0.1f;
const float  BOOMERANG_VEL_Y = 0.1f;
