#pragma once
#define ENEMY_DAMAGED_EFFECT "ENEMY-DAMAGED"
#define FIRE_BALL_DAMAGED_EFFECT "FIRE-BALL-DAMAGED"
#define SUPER_LEAF_FALL_EFFECT "SUPER-LEAF-FALL"

#define COIN_GRAVITY 0.00093f
#define COIN_BOUNCE 0.5f

#define LEAF_GRAVITY 0.00043f
#define LEAF_BOUNCE_FORCE 0.2f
#define LEAF_SPEED	    0.005f
#define LEAF_AMPLITUDE	40 
#define LEAF_BOUNCE_TIME 200

#define BOUNCE_MAX_HEIGHT 100.0f