#pragma once

#define KOOPA_STATE_MOVE			"MOVE"
#define KOOPA_STATE_WITH_DRAW		"WITH-DRAW"

#define KOOPA_SHELL_STATE_IDLE		"IDLE"
#define KOOPA_SHELL_STATE_RUN		"RUN"
#define KOOPA_SHELL_STATE_WITHDRAW	"WITH-DRAW"

#define KOOPA_SPEED					0.039f 
#define KOOPA_SHELL_SPEED			0.1f 
#define KOOPA_SHELL_DEFLECT			0.5f 
#define KOOPA_SHELL_DEFLECT_X		0.08f 

const D3DXVECTOR2 KOOPA_BBOX		(16 * 3, 27 * 3);
const D3DXVECTOR2 KOOPA_SHELL_BBOX	(16 * 3, 16 * 3);

#define KOOPA_GRAVITY				0.00093f

#define KOOPA_DIE_TIME				100
#define KOOPA_WITH_DRAW_TIME		2000
#define KOOPA_MUST_START_WITH_DRAW_TIME 6000
#define KOOPA_HEAD_SHOT_TIME		300

#define SHAKING_AMPLITUDE			5