#pragma once
#define SUPER_LEAF_FALL_EFFECT "SUPER-LEAF-FALL"

#define LEAF_GRAVITY 0.00043f
#define LEAF_BOUNCE_FORCE 0.2f
#define LEAF_SPEED	    0.005f
#define LEAF_AMPLITUDE	40 
#define LEAF_BOUNCE_TIME 200

#define BOUNCE_MAX_HEIGHT 100.0f

const D3DXVECTOR2 LEAF_BBOX(48, 48);