#pragma once

const float MARIO_GRAVITY = 0.0026f;

const float DIE_VELOCITY_Y = 0.3f;
const float DIE_JUMP = 100;
const float DIE_FALL = 200;

const float  MARIO_VENT_SPEED = 0.02f;

const float  MARIO_WALKING_SPEED = 0.24f;
const float  MARIO_RUNNING_SPEED = 0.42f;

const float  MARIO_JUMP_FORCE = 0.55f;
const float  MARIO_PUSH_FORCE = 0.55f;
const float  MARIO_FLY_FORCE = 0.0002f * 2;
const float  RACCOON_FLOAT_VELOCITY = 0.07f * 2;
const float  RACCOON_FLY_VELOCITY = -0.2f * 2;
const float  MARIO_HIGH_JUMP_HEIGHT = 180.0f ;
const float  MARIO_SUPER_JUMP_HEIGHT = 210.0f;

const float  MARIO_RUNNING_ACCELERATION = 0.001175f;
const float  MARIO_WALKING_ACCELERATION = 0.000875f;

const float  MARIO_DEFLECT_TIME = 800;
const float  MARIO_DEFLECT_Y = 0.4f;
const float  MARIO_DEFLECT_X = 0.3f;

const float MARIO_DEFLECT_BLOCK = 0.2f;

const int  FLYING_TIME = 4000;
const int FLOATING_TIME = 5000;
const int ATTACKING_TIME = 150;

const int TIME_TO_PRESS_S_TO_FLY = 200;
const int TIME_TO_PRESS_S_TO_FLOAT = 1000;

const int TIME_TO_BE_DAMAGED = 2000;
const int TIME_TO_SMOKE_EFFECT = 800;
const int TIME_TO_CHANGE_LEVEL = 800;
const int TIME_TO_CHANGE_ALPHA = 100;



const float  MARIO_BOUNCE_FORCE = 0.3f *2;

#define MARIO_STATE_IDLE				"IDLE"
#define MARIO_STATE_WALKING				"WALK"
#define MARIO_STATE_RUNNING				"RUN"
#define MARIO_STATE_HIGH_SPEED			"HIGH-SPEED"
#define MARIO_STATE_JUMP				"JUMP"
#define MARIO_STATE_HIGH_JUMP			"HIGH-JUMP"
#define MARIO_STATE_CROUCH				"CROUCH"
#define MARIO_STATE_SKID				"SKID"
#define MARIO_STATE_FALL				"FALL"
#define MARIO_STATE_ATTACK				"ATTACK"
#define MARIO_STATE_JUMP_ATTACK			"JUMP-ATTACK"
#define MARIO_STATE_FLY					"FLY"
#define MARIO_STATE_FULLFLY				"FULL-FLY"
#define MARIO_STATE_FLOAT				"FLOAT"
#define MARIO_STATE_HOLD_MOVE			"HOLD-MOVE"
#define MARIO_STATE_HOLD_IDLE			"HOLD-IDLE"
#define MARIO_STATE_HOLD_JUMP			"HOLD-JUMP"
#define MARIO_STATE_KICK				"KICK"
#define MARIO_STATE_DAMAGED				"DAMAGED"
#define MARIO_STATE_IDLE_FRONT			"IDLE-FRONT"
#define MARIO_STATE_DIE					"DIE"

#define SPACE_MARIO_MOVING_IN_CAMERA	30

#define BIG_MARIO_BBOX_WIDTH			42
#define BIG_MARIO_BBOX_HEIGHT			81
#define BIG_MARIO_CROUCH_BBOX_WIDTH		42
#define BIG_MARIO_CROUCH_BBOX_HEIGHT	42

const D3DXVECTOR2 SUPER_MARIO_BBOX(42, 81);
const D3DXVECTOR2 SUPER_MARIO_CROUCH_BBOX(42, 42);
const D3DXVECTOR2 SMALL_MARIO_BBOX(36, 45);
