#pragma once
#define SMALL_MARIO_MAP_STATE		"SMALL_MARIO"
#define BIG_MARIO_MAP_STATE			"BIG_MARIO"
#define RACCOON_MARIO_MAP_STATE		"RACCOON_MARIO"
#define FIRE_MARIO_MAP_STATE		"FIRE_MARIO"
const D3DXVECTOR2 MARIO_MAP_VELOCITY = D3DXVECTOR2(0.5f, 0.5f);