#pragma once

#define FIRE_BALL_ANIMATION				"FIRE-BALL"

#define FIRE_BALL_SPEED					0.25f 

const D3DXVECTOR2 FIRE_BALL_BBOX		(8*3, 9*3);

#define FIRE_BALL_GRAVITY				0.00093f

#define FIRE_BALL_BOUNCE_FORCE			0.3f