#include <d3dx9math.h>
#pragma once
const D3DXVECTOR2 MOVING_PLATFORM_BBOX = D3DXVECTOR2(48*3, 16*3);
const float MOVING_PLATFORM_SPEED = -0.1f;
const float MOVING_PLATFORM_FALL_VELOCITY = 0.1f;
const float MOVING_PLATFORM_GRAVITY = 0.02;