#pragma once
#define PARA_GOOMBA_IDLE "IDLE"
#define PARA_GOOMBA_WALK "WALK"
#define PARA_GOOMBA_FLY	 "FLY"

const float RED_PARAGOOMBA_HIGH_JUMP = 0.7f;
const float RED_PARAGOOMBA_LOW_JUMP = 0.2f;
const int RED_PARAGOOMBA_BREAK_TIME = 600; // miliseconds
const float DISTANCE_BETWEEN_PARA_GOOMBA_PIVOT_AND_GOOMBA_PIVOT = 13;

const D3DXVECTOR2 GOOMBA_SIZEBOX = D3DXVECTOR2(48.0f, 48.0f);
const D3DXVECTOR2 PARAGOOMBA_SIZEBOX = D3DXVECTOR2(60.0f, 72.0f);

const float RED_PARAGOOMBA_GRAVITY = 0.0024;
const float RED_PARAGOOMBA_SPEED = 0.039f * 2;