#pragma once

#define GRASS_STATE_ANIMATION "TREE"
#define HELP_STATE_ANIMATION "HELP"
#define START_STATE_ANIMATION "START"
#define SCENE_1_ANIMATION "SCENE-1"
#define SCENE_2_ANIMATION "SCENE-2"
#define SCENE_3_ANIMATION "SCENE-3"
#define SCENE_4_ANIMATION "SCENE-4"
#define SCENE_5_ANIMATION "SCENE-5"
#define SCENE_6_ANIMATION "SCENE-6"

#define MUSHROOM_ANIMATION "MUSHROOM-GATE"
#define DOMED_ANIMATION "DOMED-GATE"
#define SPADE_ANIMATION "SPADE"
#define CASTLE_ANIMATION "CASTLE"

